### ISSUE TITLE
Problems with Connection refused and connection error

### ISSUE THREAD

**Issue by s95huang** [zjunlp/EasyInstruct#25]
Hello, 
I have tried 3 different installtion methods with docker and system python enviroment on a ubuntu 22 os with CUDA etc.

The error logs states that
```

Config: {'generator': {'SelfInstructGenerator': {'target_dir': 'data/legal_dataset/', 'data_format': 'alpaca', 'seed_tasks_path': 'data/final_legal_tasks.jsonl', 'generated_instructions_path': 'generated_instructions.jsonl', 'generated_instances_path': 'generated_instances.jsonl', 'num_instructions_to_generate': 100, 'engine': 'gpt-4', 'num_prompt_instructions': 8}}}

Loaded 157 human-written seed instructions.
Loaded 0 generated instructions.
  0%|                                                                                                                                                                                      | 0/100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/httpcore/_sync/http_proxy.py", line 289, in handle_request
    connect_response = self._connection.handle_request(
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/openai/_base_client.py", line 962, in _request
    response = self._client.send(
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mvsl-4090/Desktop/Bruce/EasyInstruct/demo/run.py", line 97, in <module>
    main(args)
  File "/home/mvsl-4090/Desktop/Bruce/EasyInstruct/demo/run.py", line 53, in main
    generator.generate()
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/easyinstruct/generators/self_instruct_generator.py", line 391, in generate
    self.generate_instructions()
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/easyinstruct/generators/self_instruct_generator.py", line 260, in generate_instructions
    prompt.get_openai_result(
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/easyinstruct/prompts/base_prompt.py", line 70, in get_openai_result
    response = client.chat.completions.create(
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 643, in create
    return self._post(
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1250, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/openai/_base_client.py", line 931, in request
    return self._request(
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/openai/_base_client.py", line 986, in _request
    return self._retry_request(
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1063, in _retry_request
    return self._request(
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/openai/_base_client.py", line 986, in _request
    return self._retry_request(
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1063, in _retry_request
    return self._request(
  File "/home/mvsl-4090/.local/lib/python3.10/site-packages/openai/_base_client.py", line 996, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
  0%|                                
```

Have anyone encountered this problem?
It appears that Http reuest needs to be authenticated or something like that.
I tried the code without Docker, and the issue is still persistant.
However, when I tried the online demo, it works but locally deployment using gradio or python demo/app.py won't work

**Comment by OE-Heart** [comment]
This looks like a problem with the network connection that is calling the openai api. Can you check if your openai api key is working?

```
from openai import OpenAI

client = OpenAI(
    api_key="YOUR_OPENAI_API_KEY",
)

chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Say this is a test",
        }
    ],
    model="gpt-3.5-turbo",
)
```

**Comment by s95huang** [comment]
Resolved, thanks
closing.

**Comment by J4cksonLee** [comment]
hello i cant solve this problem. please tell me how to solve this
my email 1278352915@qq.com
