### ISSUE TITLE
Arm problem

### ISSUE THREAD

**Issue by stepankulakoff** [zjunlp/EasyInstruct#29]
Hello.
Do you have any experience running this example https://github.com/zjunlp/EasyInstruct/tree/main/examples/kg2instruction
on arm architecture, more specific apple m1.
I struggle with dependencies problems.
Thank you.

**Comment by stepankulakoff** [comment]
I have solved this problem somehow. Now I have this
kg2instruction git:(main*)python pipeline.py \
    "Taylor Swift was born on December 13, 1989 in Pennsylvania, the United States. She is a female pop singer and musician. In 2006, she released her debut self-titled music album《Taylor Swift》." \
    --language en \
    --label_db data/db/label_en.db \
    --alias_db data/db/alias_en.db \
    --alias_rev_db data/db/alias_rev_en.db \
    --relation_db data/db/relation.db \
    --relation_map_path data/other/relation_map.json \
    --enttypeid_mapper data/other/enttypeid_mapper_en.json \
    --template_path data/other/template.json \
    --schema_path data/other/all_schema.json \
    --ner_model model/ud_ontonotes_tok_pos_lem_fea_ner_srl_dep_sdp_con_xlm_base \
    --cls_model model/text_classification_en \
    --ie_llm model/OneKE \
    --nli_model model/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7 \
    --prompt_name llama2_zh \
    --device 0 \
    --print_result
2024-12-12 23:17:26,483 - INFO - __main__ - Namespace(add_relation_value=False, alias_db='data/db/alias_en.db', alias_rev_db='data/db/alias_rev_en.db', batch_size=16, chunk=5, cls_model='model/text_classification_en', device=0, enttypeid_mapper='data/other/enttypeid_mapper_en.json', ie_llm='model/OneKE', input='Taylor Swift was born on December 13, 1989 in Pennsylvania, the United States. She is a female pop singer and musician. In 2006, she released her debut self-titled music album《Taylor Swift》.', label_db='data/db/label_en.db', language='en', max_length=512, max_new_tokens=256, ner_model='model/ud_ontonotes_tok_pos_lem_fea_ner_srl_dep_sdp_con_xlm_base', nli_model='model/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7', nli_threshold=0.5, print_result=True, prompt_name='llama2_zh', relation_db='data/db/relation.db', relation_map_path='data/other/relation_map.json', relation_value_db='data/db/relation_value.db', schema_path='data/other/all_schema.json', template_path='data/other/template.json', use_vllm=False)
/opt/anaconda3/envs/kg2instruct/lib/python3.8/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
text list:  ['Taylor Swift was born on December 13, 1989 in Pennsylvania, the United States. She is a female pop singer and musician. In 2006, she released her debut self-titled music album《Taylor Swift》.']
NER results:  [[('Taylor Swift', 'PERSON', 0, 2), ('December 13 , 1989', 'DATE', 5, 9), ('Pennsylvania', 'GPE', 10, 11), ('the United States', 'GPE', 12, 15), ('2006', 'DATE', 26, 27), ('album《Taylor Swift', 'WORK_OF_ART', 34, 36)]]
entity and id results:  [[]]
Disambiguate entities:  [[]]
/opt/anaconda3/envs/kg2instruct/lib/python3.8/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Traceback (most recent call last):
  File "pipeline.py", line 199, in <module>
    main(_)
  File "pipeline.py", line 112, in main
    encoding = cls_tokenizer(texts, return_tensors='pt')
  File "/opt/anaconda3/envs/kg2instruct/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3021, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/opt/anaconda3/envs/kg2instruct/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3109, in _call_one
    return self.batch_encode_plus(
  File "/opt/anaconda3/envs/kg2instruct/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3311, in batch_encode_plus
    return self._batch_encode_plus(
  File "/opt/anaconda3/envs/kg2instruct/lib/python3.8/site-packages/transformers/models/roberta/tokenization_roberta_fast.py", line 225, in _batch_encode_plus
    return super()._batch_encode_plus(*args, **kwargs)
  File "/opt/anaconda3/envs/kg2instruct/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 562, in _batch_encode_plus
    for key in tokens_and_encodings[0][0].keys():
IndexError: list index out of range

**Comment by zxlzr** [comment]
i think this issue "IndexError: list index out of range" is caused by the data,  maybe you can print or debug the variable

**Comment by stepankulakoff** [comment]
Thank you for ur help. another question. is relation_value_db something that will be generated ?cause I can't find any download Link it, only on relation_db

**Comment by guihonghao** [comment]
Because the relation_value_db is very large, we did not upload the file. The relation_value_db is only utilized when add_relation_value=True is specified. Moreover, the impact of relation_value_db on the final results is not significant.

**Comment by stepankulakoff** [comment]
Thank you very much ! my solution was
 url = f"https://www.wikidata.org/w/api.php?action=wbgetentities&ids={entity_id}&format=json"
 response = requests.get(url)
