### ISSUE TITLE
无法读取 easyinstruct文件夹下面的engines文件夹

### ISSUE THREAD

**Issue by reloadggg** [zjunlp/EasyInstruct#4]
使用setup.py安装
import easyinstruct 无法读取 easyinstruct文件夹下面的engines文件夹，报错：
>>> import easyinstruct
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\tianchi\easyinstruct\easyinstruct\__init__.py", line 1, in <module>
    from .prompts import *
  File "d:\tianchi\easyinstruct\easyinstruct\prompts\__init__.py", line 1, in <module>
    from .base_prompt import BasePrompt
  File "d:\tianchi\easyinstruct\easyinstruct\prompts\base_prompt.py", line 7, in <module>
    from engines import llama_engine
ModuleNotFoundError: No module named 'engines'

**Comment by OE-Heart** [comment]
Sorry, it seems that there is a typo, and it has been fixed right now : )

**Comment by OE-Heart** [comment]
For the latest update, you can try installation for local development.

**Comment by reloadggg** [comment]
Okay, I will try to install it again. Thank you.

**Comment by reloadggg** [comment]
还要git下来之后里面那个readme.md文件貌似编码也有问题（不确定是不是我电脑的问题)，可以的话也麻烦修复一下
Obtaining file:///D:/TianChi/EasyInstruct
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\TianChi\EasyInstruct\setup.py", line 25, in <module>
          readme = f.read()
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 206: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by reloadggg** [comment]
貌似还是无法import,我是新创的一个conda环境，使用setup.py安装后包入如下：
Package                 Version   Editable project location
----------------------- --------- -------------------------
accelerate              0.17.1
aiohttp                 3.8.4
aiosignal               1.3.1
anthropic               0.2.7
anyio                   3.6.2
async-timeout           4.0.2
attrs                   23.1.0
certifi                 2022.12.7
charset-normalizer      3.1.0
click                   8.1.3
colorama                0.4.6
dataclasses-json        0.5.7
easyinstruct            0.0.3     d:\tianchi\easyinstruct
filelock                3.12.0
frozenlist              1.3.3
fsspec                  2023.4.0
greenlet                2.0.2
h11                     0.14.0
httpcore                0.17.0
httpx                   0.24.0
huggingface-hub         0.14.1
idna                    3.4
Jinja2                  3.1.2
joblib                  1.2.0
langchain               0.0.160
llama-cpp-python        0.1.41
llama-index             0.4.29
MarkupSafe              2.1.2
marshmallow             3.19.0
marshmallow-enum        1.5.1
mpmath                  1.3.0
multidict               6.0.4
mypy-extensions         1.0.0
networkx                3.1
nltk                    3.8.1
numexpr                 2.8.4
numpy                   1.24.3
openai                  0.27.0
openapi-schema-pydantic 1.2.4
packaging               23.1
pandas                  2.0.1
peft                    0.2.0
pip                     23.0.1
psutil                  5.9.5
pydantic                1.10.7
python-dateutil         2.8.2
pytz                    2023.3
PyYAML                  6.0
regex                   2023.5.5
requests                2.30.0
setuptools              66.0.0
six                     1.16.0
sniffio                 1.3.0
SQLAlchemy              2.0.12
sympy                   1.11.1
tenacity                8.2.2
tiktoken                0.3.3
tokenizers              0.13.3
torch                   2.0.0
tqdm                    4.65.0
transformers            4.28.1
typing_extensions       4.5.0
typing-inspect          0.8.0
tzdata                  2023.3
urllib3                 2.0.2
wheel                   0.38.4
yarl                    1.9.2

import还是报错:
Python 3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import easyinstruct
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\tianchi\easyinstruct\easyinstruct\__init__.py", line 1, in <module>
    from .prompts import *
  File "d:\tianchi\easyinstruct\easyinstruct\prompts\__init__.py", line 3, in <module>
    from .index_prompt import IndexPrompt
  File "d:\tianchi\easyinstruct\easyinstruct\prompts\index_prompt.py", line 1, in <module>
    from llama_index import SimpleDirectoryReader, LLMPredictor, GPTSimpleVectorIndex
  File "E:\anaconda3\envs\deepke\lib\site-packages\llama_index\__init__.py", line 18, in <module>
    from llama_index.indices.common.struct_store.base import SQLDocumentContextBuilder
  File "E:\anaconda3\envs\deepke\lib\site-packages\llama_index\indices\__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "E:\anaconda3\envs\deepke\lib\site-packages\llama_index\indices\keyword_table\__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "E:\anaconda3\envs\deepke\lib\site-packages\llama_index\indices\keyword_table\base.py", line 16, in <module>
    from llama_index.indices.base import DOCUMENTS_INPUT, BaseGPTIndex
  File "E:\anaconda3\envs\deepke\lib\site-packages\llama_index\indices\base.py", line 23, in <module>
    from llama_index.indices.prompt_helper import PromptHelper
  File "E:\anaconda3\envs\deepke\lib\site-packages\llama_index\indices\prompt_helper.py", line 12, in <module>
    from llama_index.langchain_helpers.chain_wrapper import LLMPredictor
  File "E:\anaconda3\envs\deepke\lib\site-packages\llama_index\langchain_helpers\chain_wrapper.py", line 10, in <module>
    from langchain.schema import BaseLanguageModel
ImportError: cannot import name 'BaseLanguageModel' from 'langchain.schema' (E:\anaconda3\envs\deepke\lib\site-packages\langchain\schema.py)

**Comment by OE-Heart** [comment]
Please try to install the 0.0.16 version of langchain using the script below:

`pip install langchain==0.0.116`
